language: python

dist: xenial

python:
  - '2.7'
  - '3.6'
  - '3.7'

env:
  - PIP_FLAGS=""
  - PIP_FLAGS="--upgrade --pre"

matrix:
  allow_failures:
    - python: '2.7'
      env: PIP_FLAGS="--upgrade --pre"
  fast_finish: true

before_install:
  - python -m pip install --upgrade pip
  - python -m pip install ${PIP_FLAGS} -r requirements.txt

install:
  # note: need --editable for executable coverage with `which ...` to work
  - python -m pip install --editable .

before_script:
  # we pin to <3.7 because astropy needs to and pip isn't good at resolving dependencies
  - python -m pip install ${PIP_FLAGS} "pytest>=2.8,<3.7" pytest-cov

script:
  # run test suite
  - python -m pytest --pyargs gwsumm --cov gwsumm
  # test executables
  - python -m coverage run --append $(which gw_summary) --help
  - python -m coverage run --append $(which gw_summary_pipe) --help
  - python -m coverage run --append $(which gwsumm-plot-triggers) --help
  - python -m coverage run --append $(which gwsumm-plot-guardian) --help

after_success:
  - python -m pip install ${PIP_FLAGS} coveralls
  - coveralls

cache:
  pip: true
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
